### ISSUE TITLE
Definir as perguntas de negócio que serão respondidas pelas funções, triggers e índices definidos

### ISSUE THREAD

**Issue by lugialo** [lugialo/projeto_banco2#11]

**Comment by anagregorioo** [comment]
Qual é a média de idade dos pacientes que realizaram procedimentos de restauração dentária nos últimos três meses, agrupada por faixas etárias, para os pacientes do sexo feminino?

**Comment by anagregorioo** [comment]
Qual é o meio de pagamento mais utlizado, nos ultimos 6 meses, entre pacientes do sexo feminino na faixa etária de 18 a 55 anos, em ordem decrescente?

**Comment by Lorelq** [comment]
Exemplifique qual a especialidade de dentistas que teve mais agendamentos nos últimos 4 meses juntamente com o procedimento que mais foi realizado pelos especialistas.

**Comment by Lorelq** [comment]
Qual o diagnóstico que teve maior incidência em pacientes com idades inferiores a 16 anos em ambos os gêneros durante os primeiros 6 meses do ano.

**Comment by lugialo** [comment]
Perguntas organizadas e definidas em https://github.com/lugialo/projeto_banco2/blob/main/perguntas_de_negocio/perguntas.sql
