### ISSUE TITLE
Criar modelo físico do banco

### ISSUE THREAD

**Issue by lugialo** [lugialo/projeto_banco2#2]
Criar o modelo físico do banco (sugestão: usar o MySQL Workbench ou similar)

**Comment by lugialo** [comment]
OBS: O nosso tema é sobre Atendimento de Odontologia.

**Comment by lugialo** [comment]
Oi @jlsilva01, boa tarde!!

Fiz o modelo físico, eu queria pedir a tua opinião pra ver se tá legal, ou se talvez eu possa mudar algo... 

(ainda não fiz nenhuma trigger, index, procedure, function, só o modelo com as ligações em si mesmo kkkk)

https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.mwb
https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.png

Aqui estão os links pro modelo (feito no MySQL Workbench) e a imagem do mesmo.

**Comment by jlsilva01** [comment]
Olá, @lugialo 

A tabela funcionário vocês não precisariam criar, ela não faz muito sentido no modelo proposto. O mais importante é ter o paciente e o dentista (e isso vocês já contemplaram no código de vocês).
No relacionamento Consulta x Pagamento, o id da consulta deve estar dentro da tabela pagamento e não o contrário.
Tente pensar no seguinte modelo, cada tabela deve ter apenas os dados que são pertinentes a ela. 
Exemplo:
No caso do relacionamento Consulta x Pagamento, uma consulta consegue ser "uma consulta" sem a identificação de pagamento? R. Sim.
Agora um pagamento consegue ser "um pagamento" sem uma identificação de qual consulta ele pertence? R. Não.

Com base nessas respostas você conseguirá entender onde cada campo de id deve ficar.

Tente fazer esse mesmo exercício para os outros relacionamentos e depois me avise de teve algum que você julgou mudar?

Abs.

**Comment by lugialo** [comment]
Boa noite professor @jlsilva01 tudo bem?

Obrigado pelas dicas! Refiz o modelo conforme as orientações passadas.

Aproveitei também pra alterar um pouco o funcionamento das tabelas. Excluí a tabela de funcionário, conforme você sugeriu, e também criei uma tabela nova consulta_procedimento para servir de tabela auxiliar entre a relação Consulta x Procedimento.

Também fiz mais algumas mudanças em outros relacionamentos, tendo ficado dessa forma:

1° - Ao invés do odontologista ter relacionamento tanto com a consulta quanto o procedimento, decidi optar por relacionar ele ao agendamento, pra ficar algo mais conciso, tendo em vista que agora optei pela tabela de procedimento apenas guardar as informações sobre os tipos de procedimento disponíveis (similar à tabela tipo_pagamento, por exemplo).

2° - Vinculei a consulta ao pagamento, de forma com que o id da consulta fique relacionado com a tabela do pagamento, como sugerido.

https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.mwb
https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.png

Essas foram as mudanças que eu julguei serem necessárias. 
Mais uma vez, gostaria de agradecer pelas dicas e pela ajuda! 😉

**Comment by jlsilva01** [comment]
Olá, @lugialo 

Ficou bem legal agora! 👏
Uma dúvida, a tabela estoque você vai manter ou vai retirar do modelo?
Se você for manter, vai precisar incluir mais algumas outras tabelas para contemplar a movimentao do estoque (entrada e saida de produtos), tipo de produto, etc no mesmo esquema que você já fez para as outras tabelas do seu modelo.

**Comment by lugialo** [comment]
Ah, verdade. Essa tabela de estoque eu pensei em remover, acho que não ficou muito legal no escopo atual...

**Comment by lugialo** [comment]
O modelo físico foi criado com sucesso.

https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.mwb
https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.png

**Comment by lugialo** [comment]
* faltou criar uma tabela pra utilizar como log

**Comment by lugialo** [comment]
Utilizei a tabela recém-criada log_pagamento, pra utilizarmos como registro de pagamentos. Também já criei as triggers necessárias, e incluí as mesmas no repositório.
