### ISSUE TITLE
Construir dicionário de dados

### ISSUE THREAD

**Issue by lugialo** [lugialo/projeto_banco2#3]

**Comment by lugialo** [comment]
@agabriellecoelho 

pode fazer baseado nesse modelo aqui:

[template_dicionario_dados.xlsx](https://github.com/user-attachments/files/15811694/template_dicionario_dados.xlsx)



Esse é o modelo físico do banco.
https://github.com/lugialo/projeto_banco2/blob/main/modelo_fisico/dump_clinica_odonto.png

**Comment by agabriellecoelho** [comment]
Em qua., 12 de jun. de 2024 às 19:17, Gabriel Antonin Pascoali <
***@***.***> escreveu:

**Comment by agabriellecoelho** [comment]
[dicionarioDeDadosConsultorio.xlsx](https://github.com/user-attachments/files/15953709/dicionarioDeDadosConsultorio.xlsx)

**Comment by lugialo** [comment]
@agabriellecoelho adiciona esse arquivo no commit, por favor

**Comment by lugialo** [comment]
(mesmo que não esteja pronto ainda)
