### ISSUE TITLE
Atualização do projeto

### ISSUE THREAD

**Issue by jlsilva01** [lugialo/projeto_banco2#5]
@lugialo somente você efetuou atualização do repositório do trabalho até este momento.
Sugiro revalidarem a distribução das tarefas para que tenha commits frequentes neste repositório indicando o trabalho contínuo do mesmo de todos da equipe.
Dúvida, me avisem.

**Comment by lugialo** [comment]
Professor, efetuamos a distribuição das tarefas restantes com o restante do grupo.
